### ISSUE TITLE
Port preCICE version to v3

### ISSUE THREAD

**Issue by carme-hp** [opendihu/opendihu#36]
**Goal:** update to the latest (breaking) release of preCICE, preCICE 3.0
**To-do**
- [x] Modify `precice.py`: change download link, configuration, installation test, etc. 
        -> no retry configuration options provided. Now we always assume that we use system's boost and eigen.
- [x] Update adapter for surface coupling to v3
       -> I commented out the volume adapter in `opendihu.h`
       -> I removed `requiresIntialData`, it will have to be added if needed
- [x] Test surface adapter for a simple example
       -> Created muscle-tendon example
- [x]  Port AMI case and compare results
- [x] Update adapter for volume coupling to v3
- [x] Test volume adapter for a simple example
- [ ] Add CI test for preCICE
- [x] Update all precice-configuration files

**Comment by carme-hp** [comment]
I have compared results for the AMI case and I think we can validate the porting: 
![Figure_1](https://github.com/opendihu/opendihu/assets/71499004/95ad917a-4be5-4623-bb43-7195bac06751)
There are indeed some differences but I think we can attribute them to the solvers itself and not preCICE (much bigger errors would be expected if it came from a porting issue).

**Comment by carme-hp** [comment]
DISCLAIMER: All of the ported xml.files have been tested that they run (in serial) and exchange information successfully, except for:
- ` with_tendons_precice/implicit_boxes`: Meshes not found
- ` with_tendons_precice/traction_current_or_reference_configuration`: Tendon participant not found

**Comment by carme-hp** [comment]
I close this, as the porting is complete and v3 is already merge to develop. It remains to include some CI test for precice.
